//! `kdb render -P | -S | --all` board materialization: v1 parity plus the
//! icon column (iss-0070) and the Blocked-by column (iss-0071).

mod common;

use common::{TestWorkspace, stderr, stdout};
use rusqlite::{Connection, params};

/// Migrate the db through the binary (a no-op `--all` render), then open it.
fn seed(ws: &TestWorkspace) -> Connection {
    let out = ws.kdb(&["render", "--all"]);
    assert!(out.status.success(), "{}", stderr(&out));
    Connection::open(ws.path(".kdb/index.db")).unwrap()
}

fn add_space(conn: &Connection, slug: &str, alias: &str, path: &str, name: &str) -> i64 {
    conn.execute(
        "INSERT INTO spaces (slug, name, alias, path) VALUES (?1, ?2, ?3, ?4)",
        params![slug, name, alias, path],
    )
    .unwrap();
    conn.last_insert_rowid()
}

fn add_project(conn: &Connection, slug: &str, alias: &str, path: &str, space: Option<i64>) -> i64 {
    conn.execute(
        "INSERT INTO projects (slug, alias, name, path, space_id) VALUES (?1, ?2, ?1, ?3, ?4)",
        params![slug, alias, path, space],
    )
    .unwrap();
    conn.last_insert_rowid()
}

/// Top-level task owned by a project (`Ok(id)`) or a space (`Err(id)`).
fn add_task(conn: &Connection, owner: Result<i64, i64>, seq: i64, title: &str, status: &str, pri: i64) -> i64 {
    let (project, space) = match owner {
        Ok(p) => (Some(p), None),
        Err(s) => (None, Some(s)),
    };
    conn.execute(
        "INSERT INTO tasks (project_id, space_id, seq, title, status, priority) VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        params![project, space, seq, title, status, pri],
    )
    .unwrap();
    conn.last_insert_rowid()
}

fn add_child(conn: &Connection, project: i64, parent: i64, child_seq: i64, title: &str) -> i64 {
    conn.execute(
        "INSERT INTO tasks (project_id, parent_id, child_seq, title) VALUES (?1, ?2, ?3, ?4)",
        params![project, parent, child_seq, title],
    )
    .unwrap();
    conn.last_insert_rowid()
}

fn block(conn: &Connection, task: i64, on: i64) {
    conn.execute("INSERT INTO task_deps (task_id, depends_on) VALUES (?1, ?2)", params![task, on]).unwrap();
}

#[test]
fn project_board_writes_index_and_task_files() {
    let ws = TestWorkspace::new();
    let conn = seed(&ws);
    let p = add_project(&conn, "kdb", "KDB", "projects/kdb", None);
    let id = add_task(&conn, Ok(p), 1, "first", "backlog", 1);
    conn.execute("UPDATE tasks SET body = '## Goal\n\nDo the thing.\n' WHERE id = ?1", [id]).unwrap();
    add_task(&conn, Ok(p), 2, "shipped", "done", 3);
    add_task(&conn, Ok(p), 3, "a | pipe", "in_progress", 2);

    let out = ws.kdb(&["render", "-P", "kdb"]);
    assert!(out.status.success(), "{}", stderr(&out));
    assert!(stdout(&out).ends_with("projects/kdb/.tasks/index.md\n"));

    let index = ws.read("projects/kdb/.tasks/index.md");
    assert!(index.starts_with("# kdb — Tasks\n\n_Generated by `kdb`. Do not edit by hand._\n\n## ![](../../../.kdb/icons/in_progress.h.svg) In Progress (1)\n\n_Actively being worked on right now._\n\n"));
    assert!(index.contains("| | Task | Title | Blocked by | Priority |\n|---|---|---|---|---|\n"));
    assert!(index.contains("| ![](../../../.kdb/icons/in_progress.svg) | [KDB-0003](T-0003.md) | a \\| pipe |  | 2 |\n"));
    assert!(index.contains("## ![](../../../.kdb/icons/backlog.h.svg) Backlog (1)\n\n_Future work; not scheduled into a cycle yet._\n\n| | Task"));
    assert!(index.contains("| ![](../../../.kdb/icons/backlog.svg) | [KDB-0001](T-0001.md) | first |  | 1 |\n"));
    // Hidden statuses collapse to a count and a command line.
    assert!(index.contains("## ![](../../../.kdb/icons/done.h.svg) Done (1)\n\n_Completed; outcome shipped or accepted._\n\n_`kdb tasks list -P kdb -s done`_\n\n"));
    assert!(index.ends_with("## Commands\n\n- `kdb tasks list -P kdb` — full list\n- `kdb tasks add \"title\" -P kdb` — add a task\n- `kdb tasks view <id>` — view a task\n"));

    let task = ws.read("projects/kdb/.tasks/T-0001.md");
    assert_eq!(task, "# KDB-0001 — first\n\n_Generated by `kdb`. Do not edit by hand._\n\n## Goal\n\nDo the thing.\n");
    assert!(ws.path("projects/kdb/.tasks/T-0003.md").exists());
    // Closed statuses get no files.
    assert!(!ws.path("projects/kdb/.tasks/T-0002.md").exists());

    // Icons are installed in the workspace root.
    for icon in ["backlog", "queued", "in_progress", "in_review", "done"] {
        assert!(ws.path(&format!(".kdb/icons/{icon}.svg")).exists(), "{icon}");
    }
}

#[test]
fn icon_path_is_relative_to_the_board() {
    let ws = TestWorkspace::new();
    let conn = seed(&ws);
    let p = add_project(&conn, "meta", "META", ".", None);
    add_task(&conn, Ok(p), 1, "root task", "today", 3);
    let deep = add_project(&conn, "deep", "DEEP", "a/b/c/d", None);
    add_task(&conn, Ok(deep), 1, "deep task", "cycle", 3);
    assert!(ws.kdb(&["render", "--all"]).status.success());
    assert!(ws.read(".tasks/index.md").contains("| ![](../.kdb/icons/queued.svg) | [META-0001]"));
    assert!(ws.read("a/b/c/d/.tasks/index.md").contains("| ![](../../../../../.kdb/icons/queued.svg) | [DEEP-0001]"));
}

#[test]
fn status_without_icon_renders_empty_cell() {
    let ws = TestWorkspace::new();
    let conn = seed(&ws);
    conn.execute("INSERT INTO task_statuses (slug, name, sort_order) VALUES ('review', 'Review', 35)", []).unwrap();
    let p = add_project(&conn, "kdb", "KDB", "projects/kdb", None);
    add_task(&conn, Ok(p), 1, "waiting", "review", 3);
    assert!(ws.kdb(&["render", "-P", "kdb"]).status.success());
    let index = ws.read("projects/kdb/.tasks/index.md");
    assert!(index.contains("## Review (1)\n\n| | Task | Title | Blocked by | Priority |\n|---|---|---|---|---|\n|  | [KDB-0001](T-0001.md) | waiting |  | 3 |\n"));
}

#[test]
fn blocked_by_column_and_frontmatter() {
    let ws = TestWorkspace::new();
    let conn = seed(&ws);
    let p = add_project(&conn, "kdb", "KDB", "projects/kdb", None);
    let s = add_space(&conn, "labs", "THR", "labs", "Lab");
    let a = add_task(&conn, Ok(p), 1, "a", "backlog", 3);
    let b = add_task(&conn, Ok(p), 2, "b", "parked", 3);
    let c = add_task(&conn, Ok(p), 3, "c", "done", 3);
    let d = add_task(&conn, Err(s), 7, "d", "today", 3);
    let child = add_child(&conn, p, a, 1, "child of a");
    let grandchild = add_child(&conn, p, child, 1, "grandchild");
    // a is blocked by an open, a parked, a done, and a cross-space task.
    for on in [d, c, b] {
        block(&conn, a, on);
    }
    block(&conn, grandchild, b);
    // A closed dependent is never blocked.
    block(&conn, c, d);

    assert!(ws.kdb(&["render", "-P", "kdb"]).status.success());
    let index = ws.read("projects/kdb/.tasks/index.md");
    assert!(index.contains("| [KDB-0001](T-0001.md) | a | KDB-0002, THR-0007 | 3 |\n"), "{index}");
    let task = ws.read("projects/kdb/.tasks/T-0001.md");
    assert!(task.starts_with("---\nblocked_by:\n  - KDB-0002\n  - THR-0007\n---\n# KDB-0001 — a\n\n"), "{task}");
    // Blockedness inherits down the parent chain; own edges come first, deduped.
    assert!(task.contains("| `KDB-0001.1` | child of a | KDB-0002, THR-0007 | 3 |\n"), "{task}");
    assert!(task.contains("| `KDB-0001.1.1` | grandchild | KDB-0002, THR-0007 | 3 |\n"), "{task}");

    // Resolving the blockers clears the column and the frontmatter.
    conn.execute("UPDATE tasks SET status = 'done' WHERE id IN (?1, ?2)", params![b, d]).unwrap();
    assert!(ws.kdb(&["render", "-P", "kdb"]).status.success());
    assert!(ws.read("projects/kdb/.tasks/index.md").contains("| [KDB-0001](T-0001.md) | a |  | 3 |\n"));
    assert!(ws.read("projects/kdb/.tasks/T-0001.md").starts_with("# KDB-0001 — a\n"));
}

#[test]
fn space_board_merges_owners_and_links_relatively() {
    let ws = TestWorkspace::new();
    let conn = seed(&ws);
    let space = add_space(&conn, "iceberg", "ICE", "labs", "Iceberg Labs");
    let adrata = add_project(&conn, "adrata", "ADR", "labs/clients/adrata", Some(space));
    add_task(&conn, Err(space), 1, "Ship site", "in_progress", 1);
    add_task(&conn, Ok(adrata), 1, "Data model", "in_progress", 3);
    add_task(&conn, Ok(adrata), 2, "Later", "backlog", 3);

    let out = ws.kdb(&["render", "-S", "iceberg"]);
    assert!(out.status.success(), "{}", stderr(&out));
    assert!(stdout(&out).ends_with("labs/.tasks/index.md\n"));
    let body = ws.read("labs/.tasks/index.md");
    assert!(body.starts_with("# Iceberg Labs — Tasks\n\n"));
    assert!(body.contains("## ![](../../.kdb/icons/in_progress.h.svg) In Progress (2)\n\n_Actively being worked on right now._\n\n| | Task | Project | Title | Blocked by | Priority |\n|---|---|---|---|---|---|\n"));
    assert!(body.contains("| ![](../../.kdb/icons/in_progress.svg) | [ICE-0001](T-0001.md) | iceberg | Ship site |  | 1 |\n| ![](../../.kdb/icons/in_progress.svg) | [ADR-0001](../clients/adrata/.tasks/T-0001.md) | adrata | Data model |  | 3 |\n"));
    // Backlog collapses on the space board.
    assert!(body.contains("## ![](../../.kdb/icons/backlog.h.svg) Backlog (1)\n\n_Future work; not scheduled into a cycle yet._\n\n_`kdb tasks list -S iceberg -s backlog`_\n\n"));
    assert!(!body.contains("Later"));
    // Both task files exist where the links point; the member board was refreshed.
    assert!(ws.path("labs/.tasks/T-0001.md").exists());
    assert!(ws.path("labs/clients/adrata/.tasks/T-0001.md").exists());
    assert!(ws.path("labs/clients/adrata/.tasks/index.md").exists());
}

#[test]
fn space_board_requires_path_and_alias() {
    let ws = TestWorkspace::new();
    let conn = seed(&ws);
    conn.execute("INSERT INTO spaces (slug, name) VALUES ('bare', 'Bare')", []).unwrap();
    let out = ws.kdb(&["render", "-S", "bare"]);
    assert!(!out.status.success());
    assert!(stderr(&out).contains("space bare has no path"));
    assert!(stderr(&ws.kdb(&["render", "-S", "nope"])).contains("space not found: nope"));
}

#[test]
fn stale_task_files_are_cleaned() {
    let ws = TestWorkspace::new();
    let conn = seed(&ws);
    let p = add_project(&conn, "kdb", "KDB", "projects/kdb", None);
    add_task(&conn, Ok(p), 1, "keep", "backlog", 3);
    ws.write("projects/kdb/.tasks/T-9999.md", "stale");
    ws.write("projects/kdb/.tasks/README.md", "keep me");
    ws.write("projects/kdb/.tasks/TODO.md", "user notes");

    assert!(ws.kdb(&["render", "-P", "kdb"]).status.success());
    assert!(!ws.path("projects/kdb/.tasks/T-9999.md").exists());
    assert!(ws.path("projects/kdb/.tasks/T-0001.md").exists());
    assert!(ws.path("projects/kdb/.tasks/README.md").exists());
    assert!(ws.path("projects/kdb/.tasks/TODO.md").exists());
}

#[test]
fn top_n_truncates_and_limit_overrides() {
    let ws = TestWorkspace::new();
    let conn = seed(&ws);
    let p = add_project(&conn, "kdb", "KDB", "projects/kdb", None);
    conn.execute("UPDATE meta SET value = '2' WHERE key = 'top_n'", []).unwrap();
    for i in 1..=5 {
        add_task(&conn, Ok(p), i, &format!("t{i}"), "backlog", 3);
    }
    assert!(ws.kdb(&["render", "-P", "kdb"]).status.success());
    assert!(ws.read("projects/kdb/.tasks/index.md").contains("## ![](../../../.kdb/icons/backlog.h.svg) Backlog (top 2 of 5)\n"));
    assert!(ws.path("projects/kdb/.tasks/T-0002.md").exists());
    assert!(!ws.path("projects/kdb/.tasks/T-0003.md").exists());

    assert!(ws.kdb(&["render", "-P", "kdb", "-n", "3"]).status.success());
    assert!(ws.read("projects/kdb/.tasks/index.md").contains("## ![](../../../.kdb/icons/backlog.h.svg) Backlog (top 3 of 5)\n"));
    assert!(ws.path("projects/kdb/.tasks/T-0003.md").exists());

    // Negative means unlimited.
    assert!(ws.kdb(&["render", "-P", "kdb", "-n", "-1"]).status.success());
    assert!(ws.read("projects/kdb/.tasks/index.md").contains("## ![](../../../.kdb/icons/backlog.h.svg) Backlog (5)\n"));
    assert!(ws.path("projects/kdb/.tasks/T-0005.md").exists());
}

#[test]
fn subtasks_render_in_parent_file_not_index() {
    let ws = TestWorkspace::new();
    let conn = seed(&ws);
    let p = add_project(&conn, "kdb", "KDB", "projects/kdb", None);
    let parent = add_task(&conn, Ok(p), 1, "Parent", "backlog", 3);
    conn.execute("UPDATE tasks SET body = 'parent body' WHERE id = ?1", [parent]).unwrap();
    let child = add_child(&conn, p, parent, 1, "Child A");
    add_child(&conn, p, child, 1, "Grandchild");
    add_child(&conn, p, parent, 2, "Child B");

    assert!(ws.kdb(&["render", "-P", "kdb"]).status.success());
    let index = ws.read("projects/kdb/.tasks/index.md");
    assert!(index.contains("KDB-0001") && index.contains("## ![](../../../.kdb/icons/backlog.h.svg) Backlog (1)\n"));
    assert!(!index.contains("Child A") && !index.contains("Grandchild"));

    let file = ws.read("projects/kdb/.tasks/T-0001.md");
    assert!(file.contains("\nparent body\n\n## Subtasks (3)\n\n| | Task | Title | Blocked by | Priority |\n|---|---|---|---|---|\n"));
    assert!(file.contains("| ![](../../../.kdb/icons/backlog.svg) | `KDB-0001.1` | Child A |  | 3 |\n| ![](../../../.kdb/icons/backlog.svg) | `KDB-0001.1.1` | Grandchild |  | 3 |\n| ![](../../../.kdb/icons/backlog.svg) | `KDB-0001.2` | Child B |  | 3 |\n"), "{file}");
    assert!(!ws.path("projects/kdb/.tasks/T-0002.md").exists());
}

#[test]
fn all_renders_non_archived_projects() {
    let ws = TestWorkspace::new();
    let conn = seed(&ws);
    add_project(&conn, "live", "LIVE", "projects/live", None);
    let old = add_project(&conn, "old", "OLD", "projects/old", None);
    conn.execute("UPDATE projects SET status = 'archived' WHERE id = ?1", [old]).unwrap();
    let out = ws.kdb(&["render", "--all"]);
    assert!(out.status.success(), "{}", stderr(&out));
    assert_eq!(stdout(&out).lines().count(), 1);
    assert!(ws.path("projects/live/.tasks/index.md").exists());
    assert!(!ws.path("projects/old/.tasks").exists());
}

#[test]
fn selector_errors() {
    let ws = TestWorkspace::new();
    let out = ws.kdb(&["render"]);
    assert!(!out.status.success());
    assert!(stderr(&out).contains("missing file argument"));
    let out = ws.kdb(&["render", "-P", "a", "--all"]);
    assert!(!out.status.success());
    assert!(stderr(&out).contains("mutually exclusive"));
    let out = ws.kdb(&["render", "-P", "nope"]);
    assert!(!out.status.success());
    assert!(stderr(&out).contains("project not found: nope"));
}
