//! One `T-NNNN.md` per materialized top-level task.

use super::queries::Task;
use super::table::{TableCtx, push_table};

pub const GENERATED_NOTE: &str = "_Generated by `kdb`. Do not edit by hand._";

/// Heading, body, and a flat depth-first Subtasks table with dotted ids.
/// Unresolved blockers go in a `blocked_by:` frontmatter list; a task with
/// none gets no frontmatter, matching v1 byte for byte.
pub fn render_task_file(ctx: &TableCtx, t: &Task, subtree: &[Task]) -> String {
    let mut out = String::new();
    let blocked = ctx.blockers.of(t.id);
    if !blocked.is_empty() {
        out.push_str("---\nblocked_by:\n");
        for b in &blocked {
            out.push_str(&format!("  - {b}\n"));
        }
        out.push_str("---\n");
    }
    out.push_str(&format!("# {} — {}\n\n{GENERATED_NOTE}\n", t.external_id, t.title));

    if let Some(body) = &t.body {
        let trimmed = body.trim_start_matches('\n');
        if !trimmed.is_empty() {
            out.push('\n');
            out.push_str(trimmed);
            if !out.ends_with('\n') {
                out.push('\n');
            }
        }
    }

    if !subtree.is_empty() {
        out.push_str(&format!("\n## Subtasks ({})\n\n", subtree.len()));
        let rows: Vec<&Task> = subtree.iter().collect();
        push_table(&mut out, ctx, &rows, None);
    }
    out
}
