//! DB → markdown materialization.
//!
//! Writes a per-project `index.md` plus one `T-{seq:04d}.md` file per
//! materialized task under `<project.path>/.tasks/`. The external task
//! id uses the project alias (e.g. `HRM-0120`) but the on-disk file is
//! project-local (`T-0120.md`), so the index sorts above the task
//! files alphabetically. Files are regenerated from the DB and should
//! not be edited by hand; stale task files (no longer in the DB) are
//! removed. `TODO.md` and other hand-written notes are left alone.

use anyhow::{Context, Result};
use rusqlite::Connection;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use crate::projects::{self, Project};
use crate::statuses::{self, Status};
use crate::tasks::{self, ListFilters, TaskView};

// -----------------------------------------------------
// projects/kdb/src/materialize.rs
//
// const TASKS_DIR                                   L50
// const INDEX_FILE                                  L51
// const GENERATED_NOTE                              L54
// pub fn materialize_project()                      L59
// pub fn materialize_all()                          L71
// fn materialize()                                  L80
// fn read_top_n()                                  L143
// fn render_index()                                L161
// fn push_description()                            L216
// fn truncate_to_top_n()                           L227
// fn push_table()                                  L238
// fn top_seq()                                     L264
// fn task_file_name()                              L275
// fn escape_md_cell()                              L279
// fn render_task_file()                            L286
// fn clean_stale_task_files()                      L315
// const PREFIX                                     L316
// mod tests                                        L347
// fn setup()                                       L355
// fn materialize_writes_todo_and_per_task()        L363
// fn stale_task_files_are_cleaned()                L411
// fn top_n_truncates_open_list()                   L458
// fn subtasks_render_in_parent_file_not_index()    L498
// -----------------------------------------------------

/// Subdir under each project's path where materialized files live.
const TASKS_DIR: &str = ".tasks";
const INDEX_FILE: &str = "index.md";

/// Header inserted at the top of every generated file.
const GENERATED_NOTE: &str = "_Generated by `kdb`. Do not edit by hand._";

/// Write the materialized index and per-task files for a single project.
///
/// Returns the path of the written index.md.
pub fn materialize_project(
    conn: &Connection,
    root: &Path,
    slug: &str,
    limit: Option<i64>,
) -> Result<PathBuf> {
    let project =
        projects::get_by_slug(conn, slug)?.with_context(|| format!("project not found: {slug}"))?;
    materialize(conn, root, &project, limit)
}

/// Write materialized files for every non-archived project.
pub fn materialize_all(conn: &Connection, root: &Path, limit: Option<i64>) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for project in projects::list(conn, false, None)? {
        let path = materialize(conn, root, &project, limit)?;
        out.push(path);
    }
    Ok(out)
}

fn materialize(
    conn: &Connection,
    root: &Path,
    project: &Project,
    limit: Option<i64>,
) -> Result<PathBuf> {
    let out_dir = root.join(&project.path).join(TASKS_DIR);
    fs::create_dir_all(&out_dir)
        .with_context(|| format!("failed to create {}", out_dir.display()))?;

    // Top-level tasks only — subtasks surface inside their parent
    // task's file via `## Subtasks`, never in the index.
    let all = tasks::list(
        conn,
        ListFilters {
            statuses: None,
            project_slug: Some(&project.slug),
            top_level_only: true,
            ..Default::default()
        },
    )?;

    let top_n = limit.unwrap_or_else(|| read_top_n(conn).unwrap_or(10));

    // Drive the index from the live `task_statuses` table so custom
    // statuses (e.g. `in_review`) render alongside the seeded ones,
    // in the configured `sort_order`.
    let status_defs = statuses::list(conn, statuses::Kind::Task)?;
    let mut by_status: HashMap<String, Vec<TaskView>> = HashMap::new();
    for t in &all {
        by_status.entry(t.task.status.clone()).or_default().push(t.clone());
    }

    // Materialize per-task files for every open and non-hidden status,
    // truncated to top_n so a runaway status (typically backlog) can't
    // blow up `.tasks/`. Closed or hidden statuses don't get files at all.
    let mut expected: HashSet<String> = HashSet::new();
    for status in &status_defs {
        if status.flag || status.is_hidden {
            continue;
        }
        let Some(tasks_in_status) = by_status.get(&status.slug) else {
            continue;
        };
        let slice = truncate_to_top_n(tasks_in_status, top_n);
        for t in slice {
            let name = task_file_name(top_seq(t));
            let task_path = out_dir.join(&name);
            let subtree = tasks::descendants(conn, t.task.id)?;
            fs::write(&task_path, render_task_file(project, t, &subtree))
                .with_context(|| format!("failed to write {}", task_path.display()))?;
            expected.insert(name);
        }
    }
    clean_stale_task_files(&out_dir, &expected)?;

    let body = render_index(project, &status_defs, &by_status, top_n);
    let out_path = out_dir.join(INDEX_FILE);
    fs::write(&out_path, body)
        .with_context(|| format!("failed to write {}", out_path.display()))?;
    Ok(out_path)
}

fn read_top_n(conn: &Connection) -> Result<i64> {
    let raw: Option<String> = conn
        .query_row("SELECT value FROM meta WHERE key = 'top_n'", [], |row| {
            row.get(0)
        })
        .map(Some)
        .or_else(|e| match e {
            rusqlite::Error::QueryReturnedNoRows => Ok(None),
            other => Err(other),
        })
        .context("failed to read meta.top_n")?;
    raw.as_deref()
        .map(str::parse::<i64>)
        .transpose()
        .context("meta.top_n is not an integer")
        .map(|v| v.unwrap_or(10))
}

fn render_index(
    project: &Project,
    status_defs: &[Status],
    by_status: &HashMap<String, Vec<TaskView>>,
    top_n: i64,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {} — Tasks\n\n", project.slug));
    out.push_str(GENERATED_NOTE);
    out.push_str("\n\n");

    let empty: Vec<TaskView> = Vec::new();
    for status in status_defs {
        let tasks = by_status.get(&status.slug).unwrap_or(&empty);
        let total = tasks.len();

        // Hidden statuses collapse to a heading + count + a single
        // command line — no table, no per-task files. Keeps the index
        // readable when a status (e.g. `done`) grows without bound.
        if status.is_hidden {
            out.push_str(&format!("## {} ({})\n\n", status.name, total));
            push_description(&mut out, status);
            out.push_str(&format!(
                "_`kdb tasks list -P {slug} -s {status_slug}`_\n\n",
                slug = project.slug,
                status_slug = status.slug,
            ));
            continue;
        }

        let slice = truncate_to_top_n(tasks, top_n);
        let header = if total > slice.len() {
            format!("## {} (top {} of {})\n\n", status.name, slice.len(), total)
        } else {
            format!("## {} ({})\n\n", status.name, total)
        };
        out.push_str(&header);
        push_description(&mut out, status);
        // Closed statuses don't have materialized task files, so render unlinked.
        push_table(&mut out, slice, /* link */ !status.flag);
    }

    out.push_str("## Commands\n\n");
    out.push_str(&format!(
        "- `kdb tasks list -P {slug}` — full list\n\
         - `kdb tasks add \"title\" -P {slug}` — add a task\n\
         - `kdb tasks view <id>` — view a task\n",
        slug = project.slug,
    ));

    out
}

/// Render the status's description as an italic line beneath its
/// section heading. No-op if the status has no description.
fn push_description(out: &mut String, status: &Status) {
    if let Some(desc) = status.description.as_deref().map(str::trim) {
        if !desc.is_empty() {
            out.push_str(&format!("_{desc}_\n\n"));
        }
    }
}

/// Truncate a task slice to at most `top_n` entries. `top_n < 0`
/// means "no limit" — historically the meta knob accepted negatives
/// as an escape hatch.
fn truncate_to_top_n(tasks: &[TaskView], top_n: i64) -> &[TaskView] {
    if top_n < 0 {
        return tasks;
    }
    let n = (top_n as usize).min(tasks.len());
    &tasks[..n]
}

/// Append a `| Task | Title | Priority |` markdown table for the
/// tasks (or an `_(none)_` line if empty). When `link` is true, the
/// Task cell is a markdown link to the task's materialized file.
fn push_table(out: &mut String, tasks: &[TaskView], link: bool) {
    if tasks.is_empty() {
        out.push_str("_(none)_\n\n");
        return;
    }
    out.push_str("| Task | Title | Priority |\n");
    out.push_str("|---|---|---|\n");
    for t in tasks {
        let id = t.external_id();
        let task_cell = if link {
            format!("[{id}]({})", task_file_name(top_seq(t)))
        } else {
            format!("`{id}`")
        };
        let title = escape_md_cell(&t.task.title);
        out.push_str(&format!(
            "| {task_cell} | {title} | {pri} |\n",
            pri = t.task.priority,
        ));
    }
    out.push('\n');
}

/// Top-level seq accessor — panics if called on a child task.
/// Materialize never iterates children directly; this enforces
/// the invariant locally.
fn top_seq(t: &TaskView) -> i64 {
    t.task
        .seq
        .expect("materialize only handles top-level tasks (parent_id IS NULL)")
}

/// On-disk name for a task's materialized file: `T-{seq:04d}.md`.
///
/// The file is project-local (lives inside `<project.path>/.tasks/`),
/// so the project alias isn't needed in the filename. Using `T-` keeps
/// `index.md` sorting above the task files alphabetically.
fn task_file_name(seq: i64) -> String {
    format!("T-{seq:04}.md")
}

fn escape_md_cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// Render a single-task file: heading + body + optional subtasks
/// table. Subtasks are listed as a flat depth-first table using the
/// dotted external ids (`KDB-0030.1`, `KDB-0030.1.2`).
fn render_task_file(_project: &Project, t: &TaskView, subtree: &[TaskView]) -> String {
    let id = t.external_id();
    let mut out = String::new();
    out.push_str(&format!("# {id} — {}\n\n", t.task.title));
    out.push_str(GENERATED_NOTE);
    out.push_str("\n");

    if let Some(body) = &t.task.body {
        let trimmed = body.trim_start_matches('\n');
        if !trimmed.is_empty() {
            out.push('\n');
            out.push_str(trimmed);
            if !out.ends_with('\n') {
                out.push('\n');
            }
        }
    }

    if !subtree.is_empty() {
        out.push_str(&format!("\n## Subtasks ({})\n\n", subtree.len()));
        push_table(&mut out, subtree, /* link */ false);
    }
    out
}

/// Delete `T-NNNN.md` files that no longer correspond to a row in the
/// DB. Only the exact pattern (uppercase `T-`, all-digit stem, `.md`
/// suffix) is touched; TODO.md and other hand-written notes are left
/// alone.
fn clean_stale_task_files(dir: &Path, expected: &HashSet<String>) -> Result<()> {
    const PREFIX: &str = "T-";
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return Ok(()),
    };
    for entry in entries {
        let entry = entry?;
        let name = match entry.file_name().into_string() {
            Ok(n) => n,
            Err(_) => continue,
        };
        if !name.starts_with(PREFIX) || !name.ends_with(".md") {
            continue;
        }
        let stem = &name[PREFIX.len()..name.len() - 3];
        if !stem.chars().all(|c| c.is_ascii_digit()) || stem.is_empty() {
            continue;
        }
        if !expected.contains(&name) {
            fs::remove_file(entry.path()).with_context(|| {
                format!(
                    "failed to remove stale task file {}",
                    entry.path().display()
                )
            })?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db;
    use crate::projects::{self as projects_mod, AddArgs as ProjAddArgs};
    use crate::tasks::{self as tasks_mod, AddArgs as TaskAddArgs};
    use crate::workspace::root::ROOT_MARKER;
    use tempfile::TempDir;

    fn setup() -> (TempDir, Connection) {
        let tmp = TempDir::new().unwrap();
        std::fs::create_dir(tmp.path().join(ROOT_MARKER)).unwrap();
        let conn = db::open(tmp.path()).unwrap();
        (tmp, conn)
    }

    #[test]
    fn materialize_writes_todo_and_per_task() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
                space_id: None,
            },
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: p.id,
                title: "first",
                body: Some("## Goal\n\nDo the thing.\n"),
                priority: Some(1),
                cycle_id: None,
                parent_id: None,
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();

        let out = materialize_project(&conn, tmp.path(), "kdb", None).unwrap();
        assert!(out.exists());
        assert!(out.ends_with("index.md"));
        let body = std::fs::read_to_string(&out).unwrap();
        assert!(body.contains("# kdb — Tasks"));
        assert!(body.contains("KDB-0001"));
        assert!(body.contains("(T-0001.md)"));
        assert!(body.contains("## Backlog (1)"));

        let task_file = tmp.path().join("projects/kdb/.tasks/T-0001.md");
        assert!(task_file.exists());
        let task_body = std::fs::read_to_string(&task_file).unwrap();
        assert!(task_body.contains("# KDB-0001 — first"));
        assert!(task_body.contains("Do the thing"));
        assert!(!task_body.contains("---\n"));
    }

    #[test]
    fn stale_task_files_are_cleaned() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
                space_id: None,
            },
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: p.id,
                title: "keep",
                body: None,
                priority: None,
                cycle_id: None,
                parent_id: None,
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();

        let tasks_dir = tmp.path().join("projects/kdb/.tasks");
        std::fs::create_dir_all(&tasks_dir).unwrap();
        // Pre-seed a stale file that should be deleted.
        std::fs::write(tasks_dir.join("T-9999.md"), "stale").unwrap();
        // And unrelated files that should NOT be deleted.
        std::fs::write(tasks_dir.join("README.md"), "keep me").unwrap();
        std::fs::write(tasks_dir.join("TODO.md"), "user notes").unwrap();

        materialize_project(&conn, tmp.path(), "kdb", None).unwrap();

        assert!(!tasks_dir.join("T-9999.md").exists());
        assert!(tasks_dir.join("T-0001.md").exists());
        assert!(tasks_dir.join("README.md").exists());
        assert!(tasks_dir.join("TODO.md").exists());
    }

    #[test]
    fn top_n_truncates_open_list() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
                space_id: None,
            },
        )
        .unwrap();
        conn.execute("UPDATE meta SET value = '2' WHERE key = 'top_n'", [])
            .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        for i in 0..5 {
            tasks_mod::add(
                &mut conn,
                TaskAddArgs {
                    project_id: p.id,
                    title: &format!("t{i}"),
                    body: None,
                    priority: None,
                    cycle_id: None,
                    parent_id: None,
                    seq: None,
                    status: None,
                    order: None,
                },
            )
            .unwrap();
        }

        let out = materialize_project(&conn, tmp.path(), "kdb", None).unwrap();
        let body = std::fs::read_to_string(&out).unwrap();
        assert!(body.contains("Backlog (top 2 of 5)"));
    }

    #[test]
    fn subtasks_render_in_parent_file_not_index() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
                space_id: None,
            },
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        let parent = tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: p.id,
                title: "Parent",
                body: Some("parent body"),
                priority: None,
                cycle_id: None,
                parent_id: None,
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();
        let child = tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: p.id,
                title: "Child A",
                body: None,
                priority: None,
                cycle_id: None,
                parent_id: Some(parent.task.id),
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: p.id,
                title: "Grandchild",
                body: None,
                priority: None,
                cycle_id: None,
                parent_id: Some(child.task.id),
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();

        let out = materialize_project(&conn, tmp.path(), "kdb", None).unwrap();
        let index_body = std::fs::read_to_string(&out).unwrap();
        // Index sees only the parent.
        assert!(index_body.contains("KDB-0001"));
        assert!(index_body.contains("Parent"));
        assert!(!index_body.contains("Child A"));
        assert!(!index_body.contains("Grandchild"));
        assert!(index_body.contains("## Backlog (1)"));

        // Children only appear in the parent's task file as a Subtasks table.
        let parent_file = tmp
            .path()
            .join("projects/kdb/.tasks/T-0001.md")
            .canonicalize()
            .unwrap();
        let parent_body = std::fs::read_to_string(&parent_file).unwrap();
        assert!(parent_body.contains("## Subtasks (2)"));
        assert!(parent_body.contains("KDB-0001.1"));
        assert!(parent_body.contains("KDB-0001.1.1"));
        assert!(parent_body.contains("Child A"));
        assert!(parent_body.contains("Grandchild"));

        // Subtasks must NOT have their own materialized files.
        assert!(!tmp.path().join("projects/kdb/.tasks/T-0002.md").exists());
    }
}
