//! DB → markdown materialization.
//!
//! Writes a per-project `index.md` plus one `T-{seq:04d}.md` file per
//! materialized task under `<project.path>/.tasks/`. The external task
//! id uses the project alias (e.g. `HRM-0120`) but the on-disk file is
//! project-local (`T-0120.md`), so the index sorts above the task
//! files alphabetically. Files are regenerated from the DB and should
//! not be edited by hand; stale task files (no longer in the DB) are
//! removed. `TODO.md` and other hand-written notes are left alone.

use anyhow::{Context, Result};
use rusqlite::Connection;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use crate::projects::{self, Project};
use crate::spaces;
use crate::statuses::{self, Status};
use crate::tasks::{self, ListFilters, TaskView};

// -----------------------------------------------------------------
// projects/kdb/src/materialize.rs
//
// const TASKS_DIR                                               L56
// const INDEX_FILE                                              L57
// const GENERATED_NOTE                                          L60
// pub fn materialize_project()                                  L65
// pub fn materialize_all()                                      L77
// fn materialize()                                              L86
// pub fn materialize_space()                                   L153
// fn group_by_status()                                         L242
// fn write_task_files()                                        L256
// fn relative_tasks_prefix()                                   L287
// fn read_top_n()                                              L308
// fn render_status_sections()                                  L333
// fn push_description()                                        L383
// fn truncate_to_top_n()                                       L394
// fn push_table()                                              L405
// fn top_seq()                                                 L430
// fn task_file_name()                                          L441
// fn escape_md_cell()                                          L445
// fn render_task_file()                                        L452
// fn clean_stale_task_files()                                  L481
// const PREFIX                                                 L482
// mod tests                                                    L513
// fn setup()                                                   L522
// fn materialize_space_groups_owners_and_links_relatively()    L530
// fn materialize_writes_todo_and_per_task()                    L613
// fn stale_task_files_are_cleaned()                            L663
// fn top_n_truncates_open_list()                               L712
// fn subtasks_render_in_parent_file_not_index()                L754
// -----------------------------------------------------------------

/// Subdir under each project's path where materialized files live.
const TASKS_DIR: &str = ".tasks";
const INDEX_FILE: &str = "index.md";

/// Header inserted at the top of every generated file.
const GENERATED_NOTE: &str = "_Generated by `kdb`. Do not edit by hand._";

/// Write the materialized index and per-task files for a single project.
///
/// Returns the path of the written index.md.
pub fn materialize_project(
    conn: &Connection,
    root: &Path,
    slug: &str,
    limit: Option<i64>,
) -> Result<PathBuf> {
    let project =
        projects::get_by_slug(conn, slug)?.with_context(|| format!("project not found: {slug}"))?;
    materialize(conn, root, &project, limit)
}

/// Write materialized files for every non-archived project.
pub fn materialize_all(conn: &Connection, root: &Path, limit: Option<i64>) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for project in projects::list(conn, false, None)? {
        let path = materialize(conn, root, &project, limit)?;
        out.push(path);
    }
    Ok(out)
}

fn materialize(
    conn: &Connection,
    root: &Path,
    project: &Project,
    limit: Option<i64>,
) -> Result<PathBuf> {
    let out_dir = root.join(&project.path).join(TASKS_DIR);
    fs::create_dir_all(&out_dir)
        .with_context(|| format!("failed to create {}", out_dir.display()))?;

    // Top-level tasks only — subtasks surface inside their parent
    // task's file via `## Subtasks`, never in the index.
    let all = tasks::list(
        conn,
        ListFilters {
            statuses: None,
            project_slug: Some(&project.slug),
            top_level_only: true,
            ..Default::default()
        },
    )?;

    let top_n = limit.unwrap_or_else(|| read_top_n(conn).unwrap_or(10));

    // Drive the index from the live `task_statuses` table so custom
    // statuses (e.g. `in_review`) render alongside the seeded ones,
    // in the configured `sort_order`.
    let status_defs = statuses::list(conn, statuses::Kind::Task)?;
    let by_status = group_by_status(&all);
    write_task_files(conn, &out_dir, &status_defs, &by_status, top_n)?;

    let mut body = String::new();
    body.push_str(&format!("# {} — Tasks\n\n", project.slug));
    body.push_str(GENERATED_NOTE);
    body.push_str("\n\n");
    render_status_sections(
        &mut body,
        "-P",
        &project.slug,
        &status_defs,
        &by_status,
        top_n,
        2,
        Some(""),
    );
    body.push_str("## Commands\n\n");
    body.push_str(&format!(
        "- `kdb tasks list -P {slug}` — full list\n\
         - `kdb tasks add \"title\" -P {slug}` — add a task\n\
         - `kdb tasks view <id>` — view a task\n",
        slug = project.slug,
    ));

    let out_path = out_dir.join(INDEX_FILE);
    fs::write(&out_path, body)
        .with_context(|| format!("failed to write {}", out_path.display()))?;
    Ok(out_path)
}

/// Write the space-level rollup board at `<space.path>/.tasks/index.md`.
///
/// The space owns `.tasks/` outright: its own space-native tasks get their
/// `T-*.md` files here, and each member project's board is refreshed in place
/// (their files stay under their own path). The index is **status-major** — one
/// merged table per horizon (In Progress, Today, Cycle, …) spanning every
/// project plus the space's own tasks, with a Project column, so the whole
/// day's work at a given horizon reads as one table. Each row links into
/// whichever `.tasks/` dir holds its file.
pub fn materialize_space(conn: &Connection, root: &Path, slug: &str) -> Result<PathBuf> {
    let space =
        spaces::get_by_slug(conn, slug)?.with_context(|| format!("space not found: {slug}"))?;
    let space_path = space.path.clone().with_context(|| {
        format!("space {slug} has no path — set one with `kdb spaces edit {slug} --path <rel>`")
    })?;
    // A space must carry an alias to own tasks / anchor a board.
    space.alias.as_deref().with_context(|| {
        format!("space {slug} has no alias — set one with `kdb spaces edit {slug} --alias <ABC>`")
    })?;

    let out_dir = root.join(&space_path).join(TASKS_DIR);
    fs::create_dir_all(&out_dir)
        .with_context(|| format!("failed to create {}", out_dir.display()))?;

    let top_n = read_top_n(conn).unwrap_or(10);
    let status_defs = statuses::list(conn, statuses::Kind::Task)?;

    // The space's own tasks — write their per-task files into the space dir.
    let space_tasks = tasks::list(
        conn,
        ListFilters {
            space_native_slug: Some(slug),
            top_level_only: true,
            ..Default::default()
        },
    )?;
    let by_status_space = group_by_status(&space_tasks);
    write_task_files(conn, &out_dir, &status_defs, &by_status_space, top_n)?;

    // Refresh each member project's own board so the links resolve, and map
    // each to its link prefix. A member sharing the space's path would clobber
    // the space dir — skip it (the space owns that path; re-path such a project).
    let members = projects::list(conn, false, Some(slug))?;
    let mut member_prefix: HashMap<String, String> = HashMap::new();
    for member in &members {
        if member.path == space_path {
            continue;
        }
        materialize(conn, root, member, None)?;
        member_prefix.insert(
            member.slug.clone(),
            relative_tasks_prefix(&space_path, &member.path),
        );
    }

    // Every task under the space — space-native plus all member-project tasks —
    // in one flat list, then bucketed by status for the merged tables.
    let all = tasks::list(
        conn,
        ListFilters {
            space_slug: Some(slug),
            top_level_only: true,
            ..Default::default()
        },
    )?;
    let by_status = group_by_status(&all);

    let mut out = String::new();
    out.push_str(&format!("# {} — Space Board\n\n", space.name));
    out.push_str(GENERATED_NOTE);
    out.push_str("\n\n");

    let empty: Vec<TaskView> = Vec::new();
    for status in &status_defs {
        let tasks = by_status.get(&status.slug).unwrap_or(&empty);
        let total = tasks.len();

        if status.is_hidden {
            out.push_str(&format!("## {} ({})\n\n", status.name, total));
            push_description(&mut out, status);
            out.push_str(&format!(
                "_`kdb tasks list -S {slug} -s {status_slug}`_\n\n",
                status_slug = status.slug,
            ));
            continue;
        }

        // Merge the horizon across all owners, most-urgent first (priority,
        // then owner, then order), and cap to top_n across the whole space.
        let mut merged: Vec<&TaskView> = tasks.iter().collect();
        merged.sort_by(|a, b| {
            a.task
                .priority
                .cmp(&b.task.priority)
                .then_with(|| a.project_slug.cmp(&b.project_slug))
                .then_with(|| a.task.order.cmp(&b.task.order))
        });
        let shown = if top_n < 0 {
            merged.len()
        } else {
            (top_n as usize).min(merged.len())
        };
        let header = if total > shown {
            format!("## {} (top {} of {})\n\n", status.name, shown, total)
        } else {
            format!("## {} ({})\n\n", status.name, total)
        };
        out.push_str(&header);
        push_description(&mut out, status);
        // Closed statuses have no materialized files → render unlinked.
        let linkable = !status.flag;
        push_space_table(&mut out, &merged[..shown], &member_prefix, linkable);
    }

    let out_path = out_dir.join(INDEX_FILE);
    fs::write(&out_path, out).with_context(|| format!("failed to write {}", out_path.display()))?;
    Ok(out_path)
}

/// Append a `| Task | Project | Title | Priority |` table for a merged,
/// cross-owner slice of the space board. Each row links into its owner's
/// `.tasks/` dir: space-native tasks sit alongside this board (no prefix),
/// member-project tasks use their relative prefix from `member_prefix`.
fn push_space_table(
    out: &mut String,
    tasks: &[&TaskView],
    member_prefix: &HashMap<String, String>,
    linkable: bool,
) {
    if tasks.is_empty() {
        out.push_str("_(none)_\n\n");
        return;
    }
    out.push_str("| Task | Project | Title | Priority |\n");
    out.push_str("|---|---|---|---|\n");
    for t in tasks {
        let id = t.external_id();
        let task_cell = if linkable {
            let prefix = if t.task.space_id.is_some() {
                ""
            } else {
                member_prefix
                    .get(&t.project_slug)
                    .map(String::as_str)
                    .unwrap_or("")
            };
            format!("[{id}]({prefix}{})", task_file_name(top_seq(t)))
        } else {
            format!("`{id}`")
        };
        out.push_str(&format!(
            "| {task_cell} | {proj} | {title} | {pri} |\n",
            proj = t.project_slug,
            title = escape_md_cell(&t.task.title),
            pri = t.task.priority,
        ));
    }
    out.push('\n');
}

/// Bucket top-level tasks by their status slug.
fn group_by_status(all: &[TaskView]) -> HashMap<String, Vec<TaskView>> {
    let mut by_status: HashMap<String, Vec<TaskView>> = HashMap::new();
    for t in all {
        by_status
            .entry(t.task.status.clone())
            .or_default()
            .push(t.clone());
    }
    by_status
}

/// Materialize per-task `T-*.md` files into `out_dir` for every open,
/// non-hidden status (truncated to `top_n`), then remove stale ones. Closed
/// or hidden statuses get no files.
fn write_task_files(
    conn: &Connection,
    out_dir: &Path,
    status_defs: &[Status],
    by_status: &HashMap<String, Vec<TaskView>>,
    top_n: i64,
) -> Result<()> {
    let mut expected: HashSet<String> = HashSet::new();
    for status in status_defs {
        if status.flag || status.is_hidden {
            continue;
        }
        let Some(tasks_in_status) = by_status.get(&status.slug) else {
            continue;
        };
        for t in truncate_to_top_n(tasks_in_status, top_n) {
            let name = task_file_name(top_seq(t));
            let task_path = out_dir.join(&name);
            let subtree = tasks::descendants(conn, t.task.id)?;
            fs::write(&task_path, render_task_file(t, &subtree))
                .with_context(|| format!("failed to write {}", task_path.display()))?;
            expected.insert(name);
        }
    }
    clean_stale_task_files(out_dir, &expected)
}

/// Relative path prefix from the space's `.tasks/` dir to a member project's
/// `.tasks/` dir, with a trailing slash (empty when the two coincide). Both
/// inputs are root-relative directory paths. Used to prefix `T-*.md` links so
/// the space board points into each member's own dir.
fn relative_tasks_prefix(space_path: &str, project_path: &str) -> String {
    let from = format!("{space_path}/{TASKS_DIR}");
    let to = format!("{project_path}/{TASKS_DIR}");
    let fc: Vec<&str> = from.split('/').filter(|s| !s.is_empty()).collect();
    let tc: Vec<&str> = to.split('/').filter(|s| !s.is_empty()).collect();
    let mut i = 0;
    while i < fc.len() && i < tc.len() && fc[i] == tc[i] {
        i += 1;
    }
    let mut parts: Vec<String> = std::iter::repeat("..".to_string())
        .take(fc.len() - i)
        .collect();
    parts.extend(tc[i..].iter().map(|s| s.to_string()));
    let rel = parts.join("/");
    if rel.is_empty() {
        String::new()
    } else {
        format!("{rel}/")
    }
}

fn read_top_n(conn: &Connection) -> Result<i64> {
    let raw: Option<String> = conn
        .query_row("SELECT value FROM meta WHERE key = 'top_n'", [], |row| {
            row.get(0)
        })
        .map(Some)
        .or_else(|e| match e {
            rusqlite::Error::QueryReturnedNoRows => Ok(None),
            other => Err(other),
        })
        .context("failed to read meta.top_n")?;
    raw.as_deref()
        .map(str::parse::<i64>)
        .transpose()
        .context("meta.top_n is not an integer")
        .map(|v| v.unwrap_or(10))
}

/// Render the status-spine sections for one owner (project or space) into
/// `out`. Headings are emitted at `level` (`##` for a per-project board, `###`
/// for a group inside the space board). `list_flag` is `-P`/`-S` for the
/// hidden-status hint command; `owner_slug` names the owner in that hint.
/// `link_prefix` prefixes each task-file link — `Some("")` for a board that
/// sits alongside its files, `Some("../sub/.tasks/")` for a member group in a
/// space board, and closed statuses always render unlinked.
fn render_status_sections(
    out: &mut String,
    list_flag: &str,
    owner_slug: &str,
    status_defs: &[Status],
    by_status: &HashMap<String, Vec<TaskView>>,
    top_n: i64,
    level: usize,
    link_prefix: Option<&str>,
) {
    let marker = "#".repeat(level);
    let empty: Vec<TaskView> = Vec::new();
    for status in status_defs {
        let tasks = by_status.get(&status.slug).unwrap_or(&empty);
        let total = tasks.len();

        // Hidden statuses collapse to a heading + count + a single
        // command line — no table, no per-task files. Keeps the index
        // readable when a status (e.g. `done`) grows without bound.
        if status.is_hidden {
            out.push_str(&format!("{marker} {} ({})\n\n", status.name, total));
            push_description(out, status);
            out.push_str(&format!(
                "_`kdb tasks list {list_flag} {owner_slug} -s {status_slug}`_\n\n",
                status_slug = status.slug,
            ));
            continue;
        }

        let slice = truncate_to_top_n(tasks, top_n);
        let header = if total > slice.len() {
            format!(
                "{marker} {} (top {} of {})\n\n",
                status.name,
                slice.len(),
                total
            )
        } else {
            format!("{marker} {} ({})\n\n", status.name, total)
        };
        out.push_str(&header);
        push_description(out, status);
        // Closed statuses don't have materialized task files, so render unlinked.
        let prefix = if status.flag { None } else { link_prefix };
        push_table(out, slice, prefix);
    }
}

/// Render the status's description as an italic line beneath its
/// section heading. No-op if the status has no description.
fn push_description(out: &mut String, status: &Status) {
    if let Some(desc) = status.description.as_deref().map(str::trim) {
        if !desc.is_empty() {
            out.push_str(&format!("_{desc}_\n\n"));
        }
    }
}

/// Truncate a task slice to at most `top_n` entries. `top_n < 0`
/// means "no limit" — historically the meta knob accepted negatives
/// as an escape hatch.
fn truncate_to_top_n(tasks: &[TaskView], top_n: i64) -> &[TaskView] {
    if top_n < 0 {
        return tasks;
    }
    let n = (top_n as usize).min(tasks.len());
    &tasks[..n]
}

/// Append a `| Task | Title | Priority |` markdown table for the
/// tasks (or an `_(none)_` line if empty). `link_prefix` `Some(p)` renders the
/// Task cell as a link to `{p}T-NNNN.md`; `None` renders an unlinked code span.
fn push_table(out: &mut String, tasks: &[TaskView], link_prefix: Option<&str>) {
    if tasks.is_empty() {
        out.push_str("_(none)_\n\n");
        return;
    }
    out.push_str("| Task | Title | Priority |\n");
    out.push_str("|---|---|---|\n");
    for t in tasks {
        let id = t.external_id();
        let task_cell = match link_prefix {
            Some(prefix) => format!("[{id}]({prefix}{})", task_file_name(top_seq(t))),
            None => format!("`{id}`"),
        };
        let title = escape_md_cell(&t.task.title);
        out.push_str(&format!(
            "| {task_cell} | {title} | {pri} |\n",
            pri = t.task.priority,
        ));
    }
    out.push('\n');
}

/// Top-level seq accessor — panics if called on a child task.
/// Materialize never iterates children directly; this enforces
/// the invariant locally.
fn top_seq(t: &TaskView) -> i64 {
    t.task
        .seq
        .expect("materialize only handles top-level tasks (parent_id IS NULL)")
}

/// On-disk name for a task's materialized file: `T-{seq:04d}.md`.
///
/// The file is project-local (lives inside `<project.path>/.tasks/`),
/// so the project alias isn't needed in the filename. Using `T-` keeps
/// `index.md` sorting above the task files alphabetically.
fn task_file_name(seq: i64) -> String {
    format!("T-{seq:04}.md")
}

fn escape_md_cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// Render a single-task file: heading + body + optional subtasks
/// table. Subtasks are listed as a flat depth-first table using the
/// dotted external ids (`KDB-0030.1`, `KDB-0030.1.2`).
fn render_task_file(t: &TaskView, subtree: &[TaskView]) -> String {
    let id = t.external_id();
    let mut out = String::new();
    out.push_str(&format!("# {id} — {}\n\n", t.task.title));
    out.push_str(GENERATED_NOTE);
    out.push_str("\n");

    if let Some(body) = &t.task.body {
        let trimmed = body.trim_start_matches('\n');
        if !trimmed.is_empty() {
            out.push('\n');
            out.push_str(trimmed);
            if !out.ends_with('\n') {
                out.push('\n');
            }
        }
    }

    if !subtree.is_empty() {
        out.push_str(&format!("\n## Subtasks ({})\n\n", subtree.len()));
        push_table(&mut out, subtree, /* unlinked */ None);
    }
    out
}

/// Delete `T-NNNN.md` files that no longer correspond to a row in the
/// DB. Only the exact pattern (uppercase `T-`, all-digit stem, `.md`
/// suffix) is touched; TODO.md and other hand-written notes are left
/// alone.
fn clean_stale_task_files(dir: &Path, expected: &HashSet<String>) -> Result<()> {
    const PREFIX: &str = "T-";
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return Ok(()),
    };
    for entry in entries {
        let entry = entry?;
        let name = match entry.file_name().into_string() {
            Ok(n) => n,
            Err(_) => continue,
        };
        if !name.starts_with(PREFIX) || !name.ends_with(".md") {
            continue;
        }
        let stem = &name[PREFIX.len()..name.len() - 3];
        if !stem.chars().all(|c| c.is_ascii_digit()) || stem.is_empty() {
            continue;
        }
        if !expected.contains(&name) {
            fs::remove_file(entry.path()).with_context(|| {
                format!(
                    "failed to remove stale task file {}",
                    entry.path().display()
                )
            })?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db;
    use crate::projects::{self as projects_mod, AddArgs as ProjAddArgs};
    use crate::spaces::{self as spaces_mod, AddArgs as SpaceAddArgs};
    use crate::tasks::{self as tasks_mod, AddArgs as TaskAddArgs};
    use crate::workspace::root::ROOT_MARKER;
    use tempfile::TempDir;

    fn setup() -> (TempDir, Connection) {
        let tmp = TempDir::new().unwrap();
        std::fs::create_dir(tmp.path().join(ROOT_MARKER)).unwrap();
        let conn = db::open(tmp.path()).unwrap();
        (tmp, conn)
    }

    #[test]
    fn materialize_space_groups_owners_and_links_relatively() {
        let (tmp, mut conn) = setup();
        let space = spaces_mod::add(
            &conn,
            SpaceAddArgs {
                slug: "acme",
                name: Some("Acme Labs"),
                alias: "ICE",
                path: Some("acme"),
                description: None,
            },
        )
        .unwrap();
        // Member project at a distinct sub-path.
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "globex",
                alias: "ADR",
                name: Some("Globex"),
                path: "acme/clients/globex",
                description: None,
                space_id: Some(space.id),
            },
        )
        .unwrap();
        let globex = projects_mod::get_by_slug(&conn, "globex").unwrap().unwrap();

        // A space-native task and a member-project task.
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: None,
                space_id: Some(space.id),
                title: "Ship site",
                body: None,
                priority: Some(1),
                cycle_id: None,
                parent_id: None,
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: Some(globex.id),
                space_id: None,
                title: "Data model",
                body: None,
                priority: None,
                cycle_id: None,
                parent_id: None,
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();

        let out = materialize_space(&conn, tmp.path(), "acme").unwrap();
        assert!(out.ends_with("acme/.tasks/index.md"));
        let body = std::fs::read_to_string(&out).unwrap();
        assert!(body.contains("# Acme Labs — Space Board"));
        // Status-major: one merged Backlog table across both owners, no
        // per-project section headings.
        assert!(body.contains("## Backlog (2)"));
        assert!(!body.contains("## ICE ·"));
        assert!(!body.contains("## ADR ·"));
        assert!(body.contains("| Task | Project | Title | Priority |"));
        // Space-native task links alongside the board; member task links into
        // its own .tasks dir — both in the same table.
        assert!(body.contains("[ICE-0001](T-0001.md)"));
        assert!(body.contains("| acme |"));
        assert!(body.contains("[ADR-0001](../clients/globex/.tasks/T-0001.md)"));
        assert!(body.contains("| globex |"));

        // Both task files actually exist where the links point.
        assert!(tmp.path().join("acme/.tasks/T-0001.md").exists());
        assert!(
            tmp.path()
                .join("acme/clients/globex/.tasks/T-0001.md")
                .exists()
        );
    }

    #[test]
    fn materialize_writes_todo_and_per_task() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
                space_id: None,
            },
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: Some(p.id),
                space_id: None,
                title: "first",
                body: Some("## Goal\n\nDo the thing.\n"),
                priority: Some(1),
                cycle_id: None,
                parent_id: None,
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();

        let out = materialize_project(&conn, tmp.path(), "kdb", None).unwrap();
        assert!(out.exists());
        assert!(out.ends_with("index.md"));
        let body = std::fs::read_to_string(&out).unwrap();
        assert!(body.contains("# kdb — Tasks"));
        assert!(body.contains("KDB-0001"));
        assert!(body.contains("(T-0001.md)"));
        assert!(body.contains("## Backlog (1)"));

        let task_file = tmp.path().join("projects/kdb/.tasks/T-0001.md");
        assert!(task_file.exists());
        let task_body = std::fs::read_to_string(&task_file).unwrap();
        assert!(task_body.contains("# KDB-0001 — first"));
        assert!(task_body.contains("Do the thing"));
        assert!(!task_body.contains("---\n"));
    }

    #[test]
    fn stale_task_files_are_cleaned() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
                space_id: None,
            },
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: Some(p.id),
                space_id: None,
                title: "keep",
                body: None,
                priority: None,
                cycle_id: None,
                parent_id: None,
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();

        let tasks_dir = tmp.path().join("projects/kdb/.tasks");
        std::fs::create_dir_all(&tasks_dir).unwrap();
        // Pre-seed a stale file that should be deleted.
        std::fs::write(tasks_dir.join("T-9999.md"), "stale").unwrap();
        // And unrelated files that should NOT be deleted.
        std::fs::write(tasks_dir.join("README.md"), "keep me").unwrap();
        std::fs::write(tasks_dir.join("TODO.md"), "user notes").unwrap();

        materialize_project(&conn, tmp.path(), "kdb", None).unwrap();

        assert!(!tasks_dir.join("T-9999.md").exists());
        assert!(tasks_dir.join("T-0001.md").exists());
        assert!(tasks_dir.join("README.md").exists());
        assert!(tasks_dir.join("TODO.md").exists());
    }

    #[test]
    fn top_n_truncates_open_list() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
                space_id: None,
            },
        )
        .unwrap();
        conn.execute("UPDATE meta SET value = '2' WHERE key = 'top_n'", [])
            .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        for i in 0..5 {
            tasks_mod::add(
                &mut conn,
                TaskAddArgs {
                    project_id: Some(p.id),
                    space_id: None,
                    title: &format!("t{i}"),
                    body: None,
                    priority: None,
                    cycle_id: None,
                    parent_id: None,
                    seq: None,
                    status: None,
                    order: None,
                },
            )
            .unwrap();
        }

        let out = materialize_project(&conn, tmp.path(), "kdb", None).unwrap();
        let body = std::fs::read_to_string(&out).unwrap();
        assert!(body.contains("Backlog (top 2 of 5)"));
    }

    #[test]
    fn subtasks_render_in_parent_file_not_index() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
                space_id: None,
            },
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        let parent = tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: Some(p.id),
                space_id: None,
                title: "Parent",
                body: Some("parent body"),
                priority: None,
                cycle_id: None,
                parent_id: None,
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();
        let child = tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: Some(p.id),
                space_id: None,
                title: "Child A",
                body: None,
                priority: None,
                cycle_id: None,
                parent_id: Some(parent.task.id),
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: Some(p.id),
                space_id: None,
                title: "Grandchild",
                body: None,
                priority: None,
                cycle_id: None,
                parent_id: Some(child.task.id),
                seq: None,
                status: None,
                order: None,
            },
        )
        .unwrap();

        let out = materialize_project(&conn, tmp.path(), "kdb", None).unwrap();
        let index_body = std::fs::read_to_string(&out).unwrap();
        // Index sees only the parent.
        assert!(index_body.contains("KDB-0001"));
        assert!(index_body.contains("Parent"));
        assert!(!index_body.contains("Child A"));
        assert!(!index_body.contains("Grandchild"));
        assert!(index_body.contains("## Backlog (1)"));

        // Children only appear in the parent's task file as a Subtasks table.
        let parent_file = tmp
            .path()
            .join("projects/kdb/.tasks/T-0001.md")
            .canonicalize()
            .unwrap();
        let parent_body = std::fs::read_to_string(&parent_file).unwrap();
        assert!(parent_body.contains("## Subtasks (2)"));
        assert!(parent_body.contains("KDB-0001.1"));
        assert!(parent_body.contains("KDB-0001.1.1"));
        assert!(parent_body.contains("Child A"));
        assert!(parent_body.contains("Grandchild"));

        // Subtasks must NOT have their own materialized files.
        assert!(!tmp.path().join("projects/kdb/.tasks/T-0002.md").exists());
    }
}
